-- create table items (
-- id serial primary key,
-- furniture_type varchar(50),
-- price int
-- );
-- insert into items (furniture_type,price)
-- values
-- ('small desk',100),
-- ('large desk',300),
-- ('fan',80)
-- ;
-- select * from items;
-- select price from items where price > 80;
-- select price from items where price <= 300;

